name: clean_architechture
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.3

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #ui
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  fluttertoast: ^8.2.5
  skeletonizer: ^1.1.1
  cached_network_image: ^3.3.1
  youtube_player_flutter: ^9.0.1
  flutter_widget_from_html: ^0.15.1
  toastification: ^2.0.0
  html: ^0.15.4
  flutter_html: any
  carousel_slider: ^4.2.1
  loadmore: ^2.0.1
  measure_size_builder: ^1.0.3
  fl_chart: ^0.68.0
  #go_router
  go_router: ^13.2.3
  #theme
  json_theme: ^6.4.1
  #blocs
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  #either_dart:
  either_dart: ^1.0.0
  #database
  shared_preferences: ^2.2.2
  #equatable
  equatable: ^2.0.5
  #di
  get_it: ^7.6.8
  #biometric
  local_auth: ^2.2.0
  #animations
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  #network
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  dio: ^5.4.2+1
  firebase_messaging: ^14.8.1
  google_fonts: ^6.2.1
  circular_profile_avatar: ^2.0.5
  dropdown_button2:
  cupertino_modal_sheet: ^1.1.0
  file_picker: ^8.0.1
  image_picker: ^1.1.1
  flutter_image_compress: ^1.1.1
  flutter_cache_manager: ^3.2.3
  simple_picker: ^0.0.6
  google_maps_flutter: ^2.6.1
  device_info_plus: ^9.1.2
  extended_nested_scroll_view: ^6.2.1
  #system
  timezone: ^0.8.0
  firebase_performance: ^0.9.4+7
  os_mime_type: ^0.0.2
  flutter_native_splash: ^2.4.0
  dart_jsonwebtoken: ^2.13.0
  collection: ^1.15.0
  url_launcher: ^6.2.6
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  flutter_libphonenumber: ^2.2.0
  rxdart: ^0.27.7
  #linkify
  flutter_linkify: ^6.0.0
  #iconly
  flutter_iconly: ^1.0.2
  flutter_otp_text_field: ^1.1.3+2
  dotted_dashed_line: ^0.0.3
  retrofit:
  build_runner:
  dartz:
  share_plus: ^9.0.0
  iconsax: ^0.0.8
  flutter_statusbarcolor_ns: ^0.5.0
  loading_animation_widget: ^1.2.1
  result_dart:
  flutter_credit_card: ^4.0.1
  card_loading: ^0.3.2
  scroll_date_picker: ^3.8.0
  pdf: ^3.10.8

  open_file: ^3.3.2
  super_tooltip: ^2.0.7
  readmore: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  flutter_downloader: ^1.11.7
  reorderables: ^0.6.0
dependency_overrides:
  intl: ^0.18.1
  webview_flutter_android: 3.16.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/themes/light_theme.json
    - assets/themes/dark_theme.json
    - assets/icons/
    - assets/icons/statements/
    - assets/icons/dnbc/
    - assets/images/
    - assets/icons/refer_friend/
    - assets/icons/shortcut/
    - assets/icons/mini_icon_short_cut/
flutter_intl:
  enabled: true