import '../models/clothes_color.dart';

class Constant{

  static List<ClothesColor> popularColors = [
  ClothesColor('Black', 0xFF000000),
  ClothesColor('White', 0xFFFFFFFF),
  ClothesColor('Red', 0xFFFF0000),
  ClothesColor('Blue', 0xFF0000FF),
  ClothesColor('Green', 0xFF00FF00),
  ClothesColor('Yellow', 0xFFFFFF00),
  ClothesColor('Pink', 0xFFFFC0CB),
  ClothesColor('Purple', 0xFF800080),
  ClothesColor('Orange', 0xFFFFA500),
  ClothesColor('Brown', 0xFFA52A2A),
  ClothesColor('Gray', 0xFF808080),
  ClothesColor('Navy', 0xFF000080),
  ClothesColor('Olive', 0xFF808000),
  ClothesColor('Maroon', 0xFF800000),
  ClothesColor('Cyan', 0xFF00FFFF),
  ];

  static List<String> fashionCategories = [
    'Shirts',
    'Pants',
    'Shorts',
    'Dresses',
    'Skirts',
    'Jackets',
    'Coats',
    'Sweaters',
    'Suits',
    'Activewear',
    'Loungewear',
    'Outerwear',
    'Accessories',
    'Footwear',
    'Undergarments',
    'Swimwear',
    'Jumpsuits and Rompers',
    'Hosiery',
    'Traditional Wear',
    'Special Occasion Wear',
  ];

  static List<String> materials = [
    "Cotton",
    "Linen",
    "Wool",
    "Silk",
    "Cashmere",
    "Hemp",
    "Bamboo",
    "Polyester",
    "Nylon",
    "Acrylic",
    "Spandex (Lycra/Elastane)",
    "Rayon (Viscose)",
    "Modal",
    "Poly-cotton (Polyester and Cotton)",
    "Wool Blends",
    "Stretch Blends",
    "Denim",
    "Corduroy",
    "Velvet",
    "Tweed",
    "Fleece",
  ];

  static List<String> clothingBrands = [
  "Nike",
  "Adidas",
  "Zara",
  "H&M",
  "Uniqlo",
  "Gucci",
  "Louis Vuitton",
  "Versace",
  "Hermès",
  "Chanel",
  "Prada",
  "Burberry",
  "Ralph Lauren",
  "Tommy Hilfiger",
  "Calvin Klein",
  "Levi’s",
  "Dolce & Gabbana",
  "Balenciaga",
  "Giorgio Armani",
  "Dior",
  "Off-White",
  "Supreme",
  "Lacoste",
  "Under Armour",
  "Puma",
  "Fendi",
  "Valentino",
  "Diesel",
  "Yves Saint Laurent",
  "Givenchy",
  "Moncler",
  "Bape (A Bathing Ape)",
  "Kenzo",
  "Patagonia",
  "Reebok",
  "Columbia",
  "Abercrombie & Fitch",
  "Hugo Boss",
  "Coach",
  "Victoria’s Secret",
  "Old Navy",
  "Forever 21",
  "Gap",
  "American Eagle",
  "A.P.C.",
  "Vans",
  "Converse",
  "New Balance",
  "Lululemon",
  "The North Face",
  "Canada Goose",
  "Kappa",
  "Timberland",
  "Massimo Dutti",
  "ASOS",
  "Bershka",
  "Stradivarius",
  "Pull & Bear",
  "Mango",
  "Ted Baker",
  "Banana Republic",
  "Dockers",
  "Champion",
  "Fila",
  "Hollister",
  "Quiksilver",
  "Billabong",
  "Roxy",
  "Volcom",
  "Oakley",
  "Hurley",
  "Element",
  "G-Star RAW",
  "Superdry",
  "Rip Curl",
  "O'Neill",
  "Jack & Jones",
  "Wrangler",
  "Lee",
  "Carhartt",
  "Schott NYC",
  "Supra",
  "Fred Perry",
  "Benetton",
  "Topshop",
  "Topman",
  "River Island",
  "J.Crew",
  "Express",
  "Urban Outfitters",
  "Anthropologie",
  "Free People",
  "Abercrombie",
  "Lucky Brand",
  "True Religion",
  "AG Jeans",
  "AllSaints",
  "Guess",
  "Tory Burch",
  "GAP",
  "COS",
  "Macy's",
  "Nordstrom",
  "Anthropologie",
  "Zadig & Voltaire",
  "Loewe",
  "Aritzia",
  "Boohoo",
  "Brandy Melville",
  "Maison Margiela",
  "Jil Sander",
  "Theory",
  "Marni",
  "Maison Kitsuné",
  "Aldo",
  "Everlane",
  "Scotch & Soda",
  "Tory Sport",
  "Mackage",
  "Lands' End",
  "Orlebar Brown",
  "James Perse",
  "Club Monaco",
  "Sandro",
  "Maje",
  "Ted Baker",
  "AllSaints",
  "Hobbs",
  "John Lewis",
  "Boden",
  "Reiss",
  "Phase Eight",
  "Coast",
  "Whistles",
  "Fat Face",
  "Seasalt",
  "Sweaty Betty",
  "Cath Kidston",
  "Mint Velvet",
  "River Island",
  "Oasis",
  "Dorothy Perkins",
  "Wallis",
  "Warehouse",
  "Karen Millen",
  "Moss Bros",
  "Aquascutum",
  "Barbour",
  "Belstaff",
  "Hunter",
  "Dr. Martens",
  "Grenson",
  "Clarks",
  "Russell & Bromley",
  "L.K.Bennett",
  "Dune",
  "Loake",
  "Church's",
  "Barker",
  "Crockett & Jones",
  "Timberland",
  "North Face",
  "Columbia Sportswear",
  "Patagonia",
  "Arc'teryx",
  "Mountain Hardwear",
  "Mammut",
  "Salomon",
  "Marmot",
  "Rab",
  "Fjällräven",
  "Norrona",
  "Haglöfs",
  "Kuhl",
  "Black Diamond",
  "Outdoor Research",
  "Sierra Designs",
  "Eddie Bauer",
  "Jack Wolfskin",
  "Berghaus",
  "Craghoppers",
  "Helly Hansen",
  "Skogstad",
  "Vaude",
  "Montane",
  "Sherpa",
  "Icebreaker",
  "Smartwool",
  "Woolrich",
  "Canada Goose",
  "Moncler",
  "Arc'teryx",
  "Patagonia",
  "Fjällräven",
  "The North Face",
  "Mammut",
  "Columbia",
  "Marmot",
  "Mountain Hardwear",
  "Rab",
  "Outdoor Research",
  "Helly Hansen",
  "Black Diamond",
  "Sierra Designs",
  "Berghaus",
  "Craghoppers",
  "Vaude",
  "Jack Wolfskin",
  "Kuhl",
  "Norrona",
  "Skogstad",
  "Montane",
  "Icebreaker",
  "Sherpa Adventure Gear",
  "Peak Performance",
  "Dale of Norway",
  "Rossignol",
  "Dynafit",
  "La Sportiva",
  "Scarpa",
  "Merrell",
  "Salewa",
  "Lowe Alpine",
  "Deuter",
  "Osprey",
  "Gregory",
  "Arcteryx",
  "Leki",
  "Black Crows",
  "Atomic",
  "Salomon",
  "Blizzard",
  "Nordica",
  "Rossignol",
  "Fischer",
  "K2",
  "Head",
  "Elan",
  "Volkl",
  "Scott",
  "Tecnica",
  "DPS",
  "Icelantic",
  "Armada",
  "Moment",
  "Line",
  "Faction",
  "G3",
  "4FRNT",
  "Lib Tech",
  "Kastle",
  "Giro",
  "Smith",
  "Poc",
  "Oakley",
  "Spyder",
  "Bogner",
  "Kjus",
  "Phenix",
  "Tenson",
  "Bergans",
  "Mammut",
  "Norrona",
  "Patagonia",
  "Fjallraven",
  "Arcteryx",
  "Columbia",
  "Mountain Hardwear",
  "Marmot",
  "Helly Hansen",
  "Rab",
  "Montane",
  "Outdoor Research",
  "Jack Wolfskin",
  "Craghoppers",
  "Berghaus",
  "Vaude",
  "Sherpa",
  "Peak Performance",
  "Dynafit",
  "Salewa",
  "La Sportiva",
  "Scarpa",
  "Mammut",
  "Gore Wear",
  "Buff",
  "Seirus",
  "Darn Tough",
  "Smartwool",
  "Icebreaker",
  "Bridgedale",
  "FITS",
  "Wigwam",
  "Thorlo",
  "Fox River",
  "Point6",
  "Farm to Feet",
  "Sockwell",
  "Balega",
  "Feetures",
  "Injinji",
  "Stance",
  "Swiftwick",
  "CEP",
  "Zensah",
  "Smartwool",
  "Icebreaker",
  "Darn Tough",
  "Bridgedale",
  "FITS",
  "Wigwam",
  "Fox River",
  "Thorlo",
  "Point6",
  "Farm to Feet",
  "Sockwell",
  "Balega",
  "Feetures",
  "Injinji",
  "Stance",
  "Swiftwick",
  "CEP",
  "Zensah",
  "Adidas",
  "Under Armour",
  "Puma",
  "Reebok",
  "New Balance",
  "Asics",
  "Saucony",
  "Brooks",
  "Mizuno",
  "Hoka One One",
  "Salomon",
  "Inov-8",
  "Altra",
  "On Running",
  "Skechers",
  "361 Degrees",
  "Topo Athletic",
  "Newton Running",
  "Xero Shoes",
  "Vivobarefoot",
  "Merrell",
  "La Sportiva",
  "Scarpa",
  "Arc'teryx",
  "Lowa",
  "Salewa",
  "Garmont",
  "Oboz",
  "Vasque",
  "KEEN",
  "Columbia",
  "The North Face",
  "Timberland",
  "Mammut",
  "Hanwag",
  "Crispi",
  "AKU",
  "Zamberlan",
  "Asolo",
  "Grisport",
  ];

}