// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLOK56xCMd1dCGp6PauVaMBGpT5ES2MTg',
    appId: '1:74621690288:web:f519d9a27c92f87b723675',
    messagingSenderId: '74621690288',
    projectId: 'agile-apex-416106',
    authDomain: 'agile-apex-416106.firebaseapp.com',
    storageBucket: 'agile-apex-416106.appspot.com',
    measurementId: 'G-6XR6FTDHJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeY88ynLTZL1XLWdR_KEn_u4M4flUMYJc',
    appId: '1:74621690288:android:91ee476528201dfb723675',
    messagingSenderId: '74621690288',
    projectId: 'agile-apex-416106',
    storageBucket: 'agile-apex-416106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyF0WlwOUhkclsdZNOp2Jg2oS7FNG3UjI',
    appId: '1:74621690288:ios:185066280203be02723675',
    messagingSenderId: '74621690288',
    projectId: 'agile-apex-416106',
    storageBucket: 'agile-apex-416106.appspot.com',
    iosBundleId: 'com.dndc',
  );

}